### PR TITLE
Updated to animated ? duration : 0 style

### PR DESCRIPTION
**Pull request by shaps80**
For me this is a lot cleaner. I didn't test that the transitioning between views (show/hide) works as expected, but I can't imagine why not?

### CODE REVIEW

**Comment by shaps80** [comment]
Thanks again for the idea, its so obvious... not sure why I haven't done this before ;)

**Comment by ethereal-engineer** [comment]
I'll test it out, as I'm currently actively using it.

**Comment by shaps80** [comment]
no worries. I didn't test so let me know if there's an issue ;)

**Comment by ethereal-engineer** [comment]
Hmmm... Unfortunately it seems that not performing the animation blocks immediately and instead putting them in the one-cycle-delayed runloop causes flicker for the intended use (i.e. the wrong UI is briefly shown). So there _is_ a difference between animation duration 0 and this approach.

**Comment by shaps80** [comment]
That's interesting. I've never seen this case. Could you describe your use case and perhaps decide etc? I'm interested in what could cause this, perhaps it's something I should be checking in my own code :-/

**Comment by ethereal-engineer** [comment]
I've updated the readme with an explanation but I will verify it again later, as I have some doubt remaining. Probably by next week some time, as I'm doing polish for the project now.

**Comment by shaps80** [comment]
Ok, let me know how you go.. I've never seen this but happy to be proven wrong ;)

**Pull request closed without merging**
